out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: false
  project: ZINC-comparison-exported-Mamba
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: false
  node_encoder: true
  node_encoder_name: LinearNode
  node_encoder_bn: false
  edge_encoder: true
  edge_encoder_name: LinearEdge
  edge_encoder_bn: false
posenc_LapPE:
  enable: true
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: l1
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Mamba_Hybrid_Degree_Noise
  n_heads: 4
  dim_hidden: 64
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: false
  batch_norm: true
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 1
  dim_inner: 64
  batchnorm: true
  act: relu
  dropout: 0.0
optim:
  clip_grad_norm: true
  optimizer: adamW
  weight_decay: 0.0001
  base_lr: 0.001
  max_epoch: 500
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
prep:
  use_exported_data: true
  exported_data_dir: /home/gzy/py/Graph-Mamba/export_system/exported/
seed: 42
