out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: false
  project: AQSOL-comparison-exported
dataset:
  format: PyG-AQSOL
  name: aqsol
  task: graph
  task_type: regression
  transductive: false
  node_encoder: true
  node_encoder_name: LinearNode
  node_encoder_bn: false
  edge_encoder: true
  edge_encoder_name: LinearEdge
  edge_encoder_bn: false
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: l1
  graph_pooling: mean
gnn:
  layers_pre_mp: 0
  layers_mp: 4
  layers_post_mp: 1
  dim_inner: 64
  layer_type: gatedgcnconv
  act: relu
  residual: true
  dropout: 0.1
optim:
  optimizer: adamW
  weight_decay: 0.0001
  base_lr: 0.001
  max_epoch: 500
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-6
prep:
  use_exported_data: true
  exported_data_dir: /home/gzy/py/Graph-Mamba/export_system/exported/
seed: 42
